//get all data
### 
GET http://localhost:5000/account

//get data by UUID
###
GET http://localhost:5000/account/f13498b9-6157-48fb-b742-63abb4143e1e

//create data
###
POST http://localhost:5000/account
Content-Type: application/json

{
    "name": "user3", 
    "username": "lujeng", 
    "password": "123", 
    "confPassword": "123", 
    "role": "user"
}

//update data
###
PATCH http://localhost:5000/account/8fbe8a27-3d64-4efc-8af6-5be2010ad667
Content-Type: application/json

{
    "name": "user", 
    "username": "user", 
    "password": "123", 
    "confPassword": "123", 
    "role": "user"
}

//delete data
###
DELETE http://localhost:5000/account/724a35a4-785a-41d8-8596-8146a636d1ae