//get all users
### 
GET http://localhost:5000/student

//get user by UUID
###
GET http://localhost:5000/student/e7bb503f-67ec-4bd9-9945-4700f5bfbfdc

//create user
###
POST http://localhost:5000/student
Content-Type: application/json

{
    "name": "reza", 
    "gender": "Laki - Laki"
}

//update user
###
PATCH http://localhost:5000/student/00bff0a1-6283-452b-a34f-79723df5a733
Content-Type: application/json

{
    "name": "lujeng", 
    "kelas": "7d",
    "gender": "Perempuan"
}

//delete user
###
DELETE http://localhost:5000/student/12c370bc-3e0f-4b82-9ffe-2b34eb05fae5